services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - node_test_models:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  node_test_models:
